const mongoose = require('mongoose');

const batchmateSchema = new mongoose.Schema({
  name: { type: String, required: true },
  emailAddress: { type: String, required: true, unique: true },
  primarySkill: { type: String, required: true },
  additionalSkills: { type: String, required: true },
  managementLevel: { type: String, required: true },
  workLocation: { type: String, required: true },
  project: { type: String, required: true },
  overallExperience: { type: String, required: true },
  currentRole: { type: String, required: true },
  jobProfile: String,
  industryKnowledge: String,
  automationSkills: String,
  devOpsSkills: String,
  cloudKnowledge: String,
  agileProject: String,
  plmDevelopment: String,
  plmTesting: String,
  plmSupport: String,
  plmAdmin: String,
  plmUpgrade: String,
  plmCadIntegration: String,
  plmInterfaceIntegration: String,
  plmSapIntegration: String,
  tcManufacturing: String,
  plmQmsIntegration: String,
  softwareEngineering: String,
  projectManagement: String,
  plmFunctional: String,
  plmMigration: String,
  plmProductConfigurators: String,
  activeWorkspaceCustomization: String,
  teamcenterModuleExperience: String,
  externalCertifications: {
    completed: String,
    completionDate: String,
    expiryDate: String
  },
  certificationsInProgress: String,
  specialCallOut: String,
}, { strict: false, timestamps: true });

module.exports = mongoose.model('Batchmate', batchmateSchema);
